[global]
developmentMode = false

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#4F46E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#1F2937"
font = "sans serif"